services:
  app:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pix_withdraw_service
      MYSQL_USER: pix_withdraw_service
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  default:
    name: hyperf-skeleton

volumes:
  db_data: